# Generated by Django 3.2.4 on 2021-07-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210701_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
            preserve_default=False,
        ),
    ]
