# Generated by Django 3.2.4 on 2021-07-02 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='lang',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
