# Generated by Django 3.2.4 on 2021-07-02 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_submission_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='memoryUsed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='timeUsed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.CharField(max_length=128, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='GroupResults',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('score', models.PositiveIntegerField(default=0)),
                ('fullScore', models.PositiveIntegerField(default=0)),
                ('timeUsed', models.PositiveIntegerField(default=0)),
                ('memoryUsed', models.PositiveIntegerField(default=0)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.submission')),
            ],
        ),
        migrations.CreateModel(
            name='CaseResults',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('verdict', models.CharField(max_length=128)),
                ('message', models.CharField(max_length=128)),
                ('timeUsed', models.PositiveIntegerField(default=0)),
                ('memoryUsed', models.PositiveIntegerField(default=0)),
                ('score', models.PositiveIntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.groupresults')),
            ],
        ),
    ]
