# Generated by Django 3.2.4 on 2021-07-02 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210702_2126'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CaseResults',
            new_name='CaseResult',
        ),
        migrations.RenameModel(
            old_name='GroupResults',
            new_name='GroupResult',
        ),
    ]
