# Generated by Django 3.2.4 on 2021-07-02 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_groupresult_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupresult',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_result', to='core.submission'),
        ),
    ]
