# Generated by Django 3.2.4 on 2021-07-09 14:51

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_caseresult_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskConfig',
            fields=[
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.task')),
                ('pdf', models.FileField(upload_to=core.models.pdfNamer)),
            ],
        ),
    ]
