# Generated by Django 3.2.4 on 2021-07-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210702_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupresult',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
