# Generated by Django 3.2.4 on 2021-07-03 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_groupresult_submission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupresult',
            name='memoryUsed',
        ),
        migrations.RemoveField(
            model_name='groupresult',
            name='timeUsed',
        ),
    ]
